//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourcesSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HumanResourcesSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление записи.
        /// </summary>
        internal static string CaptionDelete {
            get {
                return ResourceManager.GetString("CaptionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр записи.
        /// </summary>
        internal static string CaptionDetails {
            get {
                return ResourceManager.GetString("CaptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление записи.
        /// </summary>
        internal static string CaptionInsert {
            get {
                return ResourceManager.GetString("CaptionInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение записи.
        /// </summary>
        internal static string CaptionUpdate {
            get {
                return ResourceManager.GetString("CaptionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись успешно удалена..
        /// </summary>
        internal static string MessageSuccessfulDelete {
            get {
                return ResourceManager.GetString("MessageSuccessfulDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись успешно добавлена..
        /// </summary>
        internal static string MessageSuccessfulInsert {
            get {
                return ResourceManager.GetString("MessageSuccessfulInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись успешно изменена..
        /// </summary>
        internal static string MessageSuccessfulUpdate {
            get {
                return ResourceManager.GetString("MessageSuccessfulUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле «{0}» не должно быть пустым..
        /// </summary>
        internal static string ValidationErrorCannotBeEmpty {
            get {
                return ResourceManager.GetString("ValidationErrorCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле «{0}» должно соответствовать заданному формату (______@______.__)..
        /// </summary>
        internal static string ValidationErrorInvalidEmail {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле «{0}» должно соответствовать заданному формату (+7(___)-___-__-__)..
        /// </summary>
        internal static string ValidationErrorInvalidPhoneNumber {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле «{0}» должно соответствовать заданному формату (@______________)..
        /// </summary>
        internal static string ValidationErrorInvalidTelegram {
            get {
                return ResourceManager.GetString("ValidationErrorInvalidTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле «{0}» не должно содержать дату позже даты поля {1}..
        /// </summary>
        internal static string ValidationErrorMaxDate {
            get {
                return ResourceManager.GetString("ValidationErrorMaxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле «{0}» не должно содержать больше {1} символов..
        /// </summary>
        internal static string ValidationErrorMaxLength {
            get {
                return ResourceManager.GetString("ValidationErrorMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле «{0}» не должно содержать значения больше {1}..
        /// </summary>
        internal static string ValidationErrorMaxValue {
            get {
                return ResourceManager.GetString("ValidationErrorMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле «{0}» не должно содержать дату раньше даты поля {1}..
        /// </summary>
        internal static string ValidationErrorMinDate {
            get {
                return ResourceManager.GetString("ValidationErrorMinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле «{0}» должно содержать хотя бы {1} символов..
        /// </summary>
        internal static string ValidationErrorMinLength {
            get {
                return ResourceManager.GetString("ValidationErrorMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле «{0}» не должно содержать значения меньше {1}..
        /// </summary>
        internal static string ValidationErrorMinValue {
            get {
                return ResourceManager.GetString("ValidationErrorMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле «{0}» должно содержать числовые значения..
        /// </summary>
        internal static string ValidationErrorMustBeDouble {
            get {
                return ResourceManager.GetString("ValidationErrorMustBeDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле «{0}» должно содержать целое число..
        /// </summary>
        internal static string ValidationErrorMustBeInteger {
            get {
                return ResourceManager.GetString("ValidationErrorMustBeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле «{0}» не должно содержать дату позже текущей даты..
        /// </summary>
        internal static string ValidationErrorMustBeValidDate {
            get {
                return ResourceManager.GetString("ValidationErrorMustBeValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле «{0}» должно содержать только буквы..
        /// </summary>
        internal static string ValidationErrorMustContainOnlyLetters {
            get {
                return ResourceManager.GetString("ValidationErrorMustContainOnlyLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить выбранную запись?.
        /// </summary>
        internal static string WarningConfirmDelete {
            get {
                return ResourceManager.GetString("WarningConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, выберите одно из значений поля {0}..
        /// </summary>
        internal static string WarningSelectComboBoxValue {
            get {
                return ResourceManager.GetString("WarningSelectComboBoxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, выберите запись для удаления..
        /// </summary>
        internal static string WarningSelectEntryToDelete {
            get {
                return ResourceManager.GetString("WarningSelectEntryToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, выберите запись для изменения..
        /// </summary>
        internal static string WarningSelectEntryToUpdate {
            get {
                return ResourceManager.GetString("WarningSelectEntryToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, выберите запись для удаления..
        /// </summary>
        internal static string WarningSelectEntryToView {
            get {
                return ResourceManager.GetString("WarningSelectEntryToView", resourceCulture);
            }
        }
    }
}
